# Generated by Django 5.2.7 on 2025-10-07 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('session_type', models.CharField(choices=[('reading', 'Reading'), ('quiz', 'Quiz'), ('review', 'Review')], default='quiz', max_length=20)),
                ('quiz_type', models.CharField(blank=True, choices=[('mcq', 'MCQ'), ('saq', 'SAQ'), ('laq', 'LAQ')], max_length=10, null=True)),
                ('questions_attempted', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('time_spent', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quizzes_taken', models.IntegerField(default=0)),
                ('total_questions_attempted', models.IntegerField(default=0)),
                ('total_correct_answers', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0)),
                ('strengths', models.JSONField(default=dict)),
                ('weaknesses', models.JSONField(default=dict)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'User progress',
            },
        ),
        migrations.CreateModel(
            name='LearningGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('target_date', models.DateField()),
                ('target_score', models.FloatField(default=80)),
                ('current_progress', models.FloatField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
